export const PROVINCES = [
  "Aceh",
  "Sumatera Utara",
  "Sumatera Barat",
  "Riau",
  "Kepulauan Riau",
  "Jambi",
  "Sumatera Selatan",
  "Bangka Belitung",
  "Bengkulu",
  "Lampung",
  "DKI Jakarta",
  "Banten",
  "Jawa Barat",
  "Jawa Tengah",
  "DI Yogyakarta",
  "Jawa Timur",
  "Bali",
  "Nusa Tenggara Barat",
  "Nusa Tenggara Timur",
  "Kalimantan Barat",
  "Kalimantan Tengah",
  "Kalimantan Selatan",
  "Kalimantan Timur",
  "Kalimantan Utara",
  "Sulawesi Utara",
  "Gorontalo",
  "Sulawesi Tengah",
  "Sulawesi Barat",
  "Sulawesi Selatan",
  "Sulawesi Tenggara",
  "Maluku",
  "Maluku Utara",
  "Papua",
  "Papua Barat",
  "Papua Barat Daya",
  "Papua Selatan",
  "Papua Tengah",
  "Papua Pegunungan"
];

export const CITIES_BY_PROVINCE: Record<string, string[]> = {
  "Aceh": ["Banda Aceh", "Sabang", "Lhokseumawe", "Langsa", "Subulussalam", "Aceh Besar", "Aceh Barat", "Aceh Utara", "Aceh Timur", "Aceh Selatan", "Aceh Singkil", "Aceh Tamiang", "Aceh Tenggara", "Gayo Lues", "Bener Meriah", "Pidie", "Pidie Jaya", "Bireuen", "Aceh Jaya", "Nagan Raya", "Aceh Barat Daya", "Simeulue"],
  "Sumatera Utara": ["Medan", "Binjai", "Tebing Tinggi", "Pematangsiantar", "Tanjungbalai", "Sibolga", "Padangsidimpuan", "Gunungsitoli", "Deli Serdang", "Karo", "Samosir", "Toba", "Tapanuli Utara", "Tapanuli Tengah", "Tapanuli Selatan", "Mandailing Natal", "Nias", "Nias Selatan", "Nias Barat", "Nias Utara", "Langkat", "Serdang Bedagai", "Batu Bara", "Asahan", "Labuhanbatu", "Labuhanbatu Utara", "Labuhanbatu Selatan", "Humbang Hasundutan", "Pakpak Bharat", "Dairi", "Simalungun", "Padang Lawas", "Padang Lawas Utara"],
  "Sumatera Barat": ["Padang", "Bukittinggi", "Payakumbuh", "Solok", "Sawahlunto", "Padang Panjang", "Pariaman", "Pesisir Selatan", "Solok Selatan", "Dharmasraya", "Sijunjung", "Tanah Datar", "Padang Pariaman", "Agam", "Pasaman", "Pasaman Barat", "Lima Puluh Kota", "Kepulauan Mentawai"],
  "Riau": ["Pekanbaru", "Dumai", "Kampar", "Bengkalis", "Indragiri Hulu", "Indragiri Hilir", "Siak", "Pelalawan", "Rokan Hulu", "Rokan Hilir", "Kepulauan Meranti", "Kuantan Singingi"],
  "Kepulauan Riau": ["Tanjungpinang", "Batam", "Bintan", "Karimun", "Natuna", "Kepulauan Anambas", "Lingga"],
  "Jambi": ["Jambi", "Sungai Penuh", "Muaro Jambi", "Batanghari", "Bungo", "Tebo", "Merangin", "Sarolangun", "Tanjung Jabung Barat", "Tanjung Jabung Timur", "Kerinci"],
  "Sumatera Selatan": ["Palembang", "Prabumulih", "Lubuklinggau", "Pagar Alam", "Banyuasin", "Ogan Komering Ilir", "Ogan Komering Ulu", "Ogan Komering Ulu Timur", "Ogan Komering Ulu Selatan", "Muara Enim", "Lahat", "Musi Banyuasin", "Musi Rawas", "Musi Rawas Utara", "Empat Lawang", "Penukal Abab Lematang Ilir", "Ogan Ilir"],
  "Bangka Belitung": ["Pangkalpinang", "Bangka", "Belitung", "Bangka Barat", "Bangka Tengah", "Bangka Selatan", "Belitung Timur"],
  "Bengkulu": ["Bengkulu", "Rejang Lebong", "Bengkulu Utara", "Bengkulu Selatan", "Mukomuko", "Seluma", "Kaur", "Kepahiang", "Lebong", "Bengkulu Tengah"],
  "Lampung": ["Bandar Lampung", "Metro", "Lampung Selatan", "Lampung Tengah", "Lampung Utara", "Lampung Barat", "Tanggamus", "Pringsewu", "Pesawaran", "Pesisir Barat", "Way Kanan", "Lampung Timur", "Tulang Bawang", "Tulang Bawang Barat", "Mesuji"],
  "DKI Jakarta": ["Jakarta Pusat", "Jakarta Utara", "Jakarta Barat", "Jakarta Selatan", "Jakarta Timur", "Kepulauan Seribu"],
  "Banten": ["Serang", "Tangerang", "Cilegon", "Tangerang Selatan", "Lebak", "Pandeglang", "Tangerang Kabupaten", "Serang Kabupaten"],
  "Jawa Barat": ["Bandung", "Bogor", "Depok", "Bekasi", "Cirebon", "Tasikmalaya", "Cimahi", "Sukabumi", "Banjar", "Sumedang", "Garut", "Cianjur", "Karawang", "Subang", "Purwakarta", "Majalengka", "Kuningan", "Indramayu", "Ciamis", "Pangandaran", "Tasikmalaya Kabupaten", "Cirebon Kabupaten", "Bekasi Kabupaten", "Bandung Barat", "Bandung Kabupaten", "Bogor Kabupaten", "Sukabumi Kabupaten"],
  "Jawa Tengah": ["Semarang", "Surakarta (Solo)", "Magelang", "Pekalongan", "Tegal", "Salatiga", "Banyumas", "Cilacap", "Kudus", "Jepara", "Klaten", "Brebes", "Semarang Kabupaten", "Purbalingga", "Banjarnegara", "Kebumen", "Purworejo", "Wonosobo", "Boyolali", "Sukoharjo", "Wonogiri", "Karanganyar", "Sragen", "Grobogan", "Blora", "Rembang", "Pati", "Demak", "Temanggung", "Kendal", "Batang", "Pekalongan Kabupaten", "Pemalang", "Tegal Kabupaten"],
  "DI Yogyakarta": ["Yogyakarta", "Sleman", "Bantul", "Gunungkidul", "Kulon Progo"],
  "Jawa Timur": ["Surabaya", "Malang", "Batu", "Kediri", "Madiun", "Blitar", "Pasuruan", "Probolinggo", "Mojokerto", "Banyuwangi", "Jember", "Sidoarjo", "Gresik", "Tuban", "Lamongan", "Bojonegoro", "Ngawi", "Magetan", "Ponorogo", "Pacitan", "Trenggalek", "Tulungagung", "Blitar Kabupaten", "Kediri Kabupaten", "Malang Kabupaten", "Pasuruan Kabupaten", "Probolinggo Kabupaten", "Lumajang", "Bondowoso", "Situbondo", "Nganjuk", "Jombang", "Mojokerto Kabupaten", "Bangkalan", "Sampang", "Pamekasan", "Sumenep"],
  "Bali": ["Denpasar", "Badung", "Gianyar", "Buleleng", "Tabanan", "Karangasem", "Klungkung", "Bangli", "Jembrana"],
  "Nusa Tenggara Barat": ["Mataram", "Bima", "Lombok Barat", "Lombok Tengah", "Lombok Timur", "Lombok Utara", "Sumbawa", "Sumbawa Barat", "Dompu", "Bima Kabupaten"],
  "Nusa Tenggara Timur": ["Kupang", "Ende", "Sikka", "Manggarai", "Manggarai Barat (Labuan Bajo)", "Alor", "Belu", "Sumba Timur", "Sumba Barat", "Sumba Tengah", "Sumba Barat Daya", "Kupang Kabupaten", "Timor Tengah Selatan", "Timor Tengah Utara", "Rote Ndao", "Saburaijua", "Lembata", "Flores Timur", "Nagekeo", "Ngada", "Manggarai Timur"],
  "Kalimantan Barat": ["Pontianak", "Singkawang", "Kubu Raya", "Mempawah", "Sambas", "Sintang", "Ketapang", "Landak", "Sanggau", "Sekadau", "Melawi", "Kapuas Hulu", "Kayong Utara", "Bengkayang"],
  "Kalimantan Tengah": ["Palangka Raya", "Kotawaringin Timur", "Kotawaringin Barat", "Kapuas", "Barito Utara", "Katingan", "Seruyan", "Sukamara", "Lamandau", "Pulang Pisau", "Gunung Mas", "Barito Selatan", "Barito Timur", "Murung Raya"],
  "Kalimantan Selatan": ["Banjarmasin", "Banjarbaru", "Banjar", "Tanah Bumbu", "Kotabaru", "Barito Kuala", "Tabalong", "Tapin", "Hulu Sungai Selatan", "Hulu Sungai Tengah", "Hulu Sungai Utara", "Balangan", "Tanah Laut"],
  "Kalimantan Timur": ["Samarinda", "Balikpapan", "Bontang", "Kutai Kartanegara", "Kutai Timur", "Kutai Barat", "Berau", "Penajam Paser Utara", "Paser", "Mahakam Ulu"],
  "Kalimantan Utara": ["Tanjung Selor", "Tarakan", "Nunukan", "Malinau", "Bulungan", "Tana Tidung"],
  "Sulawesi Utara": ["Manado", "Bitung", "Tomohon", "Kotamobagu", "Minahasa", "Minahasa Utara", "Minahasa Selatan", "Minahasa Tenggara", "Kepulauan Sangihe", "Kepulauan Talaud", "Kepulauan Siau Tagulandang Biaro", "Bolaang Mongondow", "Bolaang Mongondow Utara", "Bolaang Mongondow Selatan", "Bolaang Mongondow Timur"],
  "Gorontalo": ["Gorontalo", "Limboto", "Boalemo", "Bone Bolango", "Pohuwato", "Gorontalo Utara"],
  "Sulawesi Tengah": ["Palu", "Donggala", "Poso", "Luwuk", "Tolitoli", "Morowali", "Banggai", "Parigi Moutong", "Sigi", "Tojo Una-Una", "Banggai Kepulauan", "Banggai Laut", "Buol", "Morowali Utara"],
  "Sulawesi Barat": ["Mamuju", "Majene", "Polewali Mandar", "Mamasa", "Pasangkayu", "Mamuju Tengah"],
  "Sulawesi Selatan": ["Makassar", "Parepare", "Palopo", "Gowa", "Maros", "Pangkajene Kepulauan", "Barru", "Bone", "Bulukumba", "Toraja Utara", "Tana Toraja", "Luwu Utara", "Luwu Timur", "Luwu", "Enrekang", "Pinrang", "Sidrap", "Wajo", "Soppeng", "Sinjai", "Bantaeng", "Jeneponto", "Takalar", "Kepulauan Selayar"],
  "Sulawesi Tenggara": ["Kendari", "Bau-Bau", "Kolaka", "Konawe", "Muna", "Buton", "Wakatobi", "Bombana", "Konawe Utara", "Konawe Selatan", "Konawe Kepulauan", "Kolaka Utara", "Kolaka Timur", "Buton Utara", "Buton Selatan", "Buton Tengah", "Muna Barat"],
  "Maluku": ["Ambon", "Tual", "Maluku Tengah", "Maluku Tenggara", "Kepulauan Aru", "Kepulauan Tanimbar", "Buru", "Buru Selatan", "Seram Bagian Barat", "Seram Bagian Timur", "Maluku Barat Daya"],
  "Maluku Utara": ["Ternate", "Tidore Kepulauan", "Halmahera Utara", "Halmahera Selatan", "Halmahera Barat", "Halmahera Tengah", "Halmahera Timur", "Kepulauan Sula", "Pulau Morotai", "Pulau Taliabu"],
  "Papua": ["Jayapura", "Keerom", "Sarmi", "Mamberamo Raya", "Biak Numfor", "Kepulauan Yapen", "Waropen", "Supiori"],
  "Papua Barat": ["Manokwari", "Fakfak", "Kaimana", "Teluk Wondama", "Teluk Bintuni", "Pegunungan Arfak", "Manokwari Selatan"],
  "Papua Barat Daya": ["Sorong", "Raja Ampat", "Sorong Selatan", "Maybrat", "Tambrauw", "Mamberamo"],
  "Papua Selatan": ["Merauke", "Boven Digoel", "Mappi", "Asmat"],
  "Papua Tengah": ["Nabire", "Mimika (Timika)", "Paniai", "Puncak", "Puncak Jaya", "Dogiyai", "Deiyai", "Intan Jaya"],
  "Papua Pegunungan": ["Wamena (Jayawijaya)", "Lanny Jaya", "Tolikara", "Yahukimo", "Yalimo", "Nduga", "Pegunungan Bintang", "Mamberamo Tengah"]
};
