import 'package:customer_mobile/models/review.dart';

class TripPackage {
  final int id;
  final int providerId;
  final String providerName;
  final String providerAvatar;
  final String name;
  final String category;
  final String destination;
  final int price;
  final int quotaUsed;
  final int quotaMax;
  final String schedule; // comma-separated or date format
  final String status; // Aktif, Draft, Nonaktif
  final double rating;

  // Additional UI-centric properties for high-fidelity presentation
  final String duration;
  final String tripType; // Open Trip, Private Trip, Honeymoon, Family, Corporate
  final int minParticipants;
  final int availableSeats;
  final String description;
  final List<String> images;
  final List<String> itinerary;
  final List<String> facilities;
  final List<String> includes;
  final List<String> excludes;
  final String meetingPoint;
  final int reviewCount;
  final List<ReviewItem> reviews;
  final List<String> highlights;

  int get quotaMin => minParticipants;

  TripPackage({
    required this.id,
    required this.providerId,
    this.providerName = 'TemenTrip Official Provider',
    this.providerAvatar = 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200',
    required this.name,
    this.category = 'Diving & Snorkeling',
    required this.destination,
    required this.price,
    required this.quotaUsed,
    required this.quotaMax,
    required this.schedule,
    required this.status,
    required this.rating,
    required this.duration,
    required this.tripType,
    required this.minParticipants,
    required this.availableSeats,
    required this.description,
    required this.images,
    required this.itinerary,
    required this.facilities,
    required this.includes,
    required this.excludes,
    required this.meetingPoint,
    required this.reviewCount,
    this.reviews = const [],
    this.highlights = const [],
  });

  factory TripPackage.fromJson(Map<String, dynamic> json) {
    return TripPackage(
      id: json['id'] as int,
      providerId: json['providerId'] as int? ?? 1,
      providerName: json['providerName'] as String? ?? 'TemenTrip Official Provider',
      providerAvatar: json['providerAvatar'] as String? ?? 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200',
      name: json['name'] as String? ?? 'Paket Wisata',
      category: json['category'] as String? ?? 'City Tour',
      destination: json['destination'] as String? ?? 'Indonesia',
      price: (json['price'] as num? ?? 0).toInt(),
      quotaUsed: json['quotaUsed'] as int? ?? 0,
      quotaMax: json['quotaMax'] as int? ?? 15,
      schedule: json['schedule'] as String? ?? '16 Sep 2026 - 17 Sep 2026 (2 Hari)',
      status: json['status'] as String? ?? 'Aktif',
      rating: (json['rating'] as num? ?? 4.8).toDouble(),
      duration: json['duration'] as String? ?? '3 Hari 2 Malam',
      tripType: json['tripType'] as String? ?? 'Open Trip',
      minParticipants: json['quotaMin'] as int? ?? json['minParticipants'] as int? ?? 4,
      availableSeats: ((json['quotaMax'] as int? ?? 15) - (json['quotaUsed'] as int? ?? 0)),
      description: json['description'] as String? ?? 'Spesialis open trip gunung dengan pengalaman tim profesional dan fasilitas lengkap.',
      images: json['images'] is List ? List<String>.from(json['images']) : [json['image'] as String? ?? 'https://images.unsplash.com/photo-1589308078059-be1415eab4c3?w=800'],
      itinerary: List<String>.from(json['itinerary'] ?? []),
      facilities: List<String>.from(json['facilities'] ?? []),
      includes: List<String>.from(json['includes'] ?? []),
      excludes: List<String>.from(json['excludes'] ?? []),
      meetingPoint: json['meetingPoint'] as String? ?? 'Bandara / Stasiun Terdekat',
      reviewCount: json['reviewCount'] as int? ?? 100,
      reviews: json['reviews'] != null
          ? (json['reviews'] as List).map((r) => ReviewItem.fromJson(r as Map<String, dynamic>)).toList()
          : [],
      highlights: List<String>.from(json['highlights'] ?? []),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'providerId': providerId,
      'providerName': providerName,
      'providerAvatar': providerAvatar,
      'name': name,
      'category': category,
      'destination': destination,
      'price': price,
      'quotaUsed': quotaUsed,
      'quotaMax': quotaMax,
      'schedule': schedule,
      'status': status,
      'rating': rating,
      'duration': duration,
      'tripType': tripType,
      'minParticipants': minParticipants,
      'availableSeats': availableSeats,
      'description': description,
      'images': images,
      'itinerary': itinerary,
      'facilities': facilities,
      'includes': includes,
      'excludes': excludes,
      'meetingPoint': meetingPoint,
      'reviewCount': reviewCount,
      'reviews': reviews.map((r) => r.toJson()).toList(),
      'highlights': highlights,
    };
  }

  // Exact 1-to-1 synced database from provider-web CustomerLandingPage.tsx DEFAULT_PACKAGES & screenshot
  static final List<TripPackage> allPackages = [
    TripPackage(
      id: 1,
      providerId: 1,
      providerName: 'Wisata Nusantara',
      providerAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200',
      name: 'Rumah Ayu Ting-Ting',
      category: 'Wisata Budaya & Sejarah',
      tripType: 'Open Trip',
      destination: 'Jawa Barat',
      price: 2000000,
      quotaUsed: 3,
      quotaMax: 15,
      minParticipants: 5,
      availableSeats: 12,
      schedule: '16 September 2026 - 18 September 2026 (3 Hari)',
      duration: '3 Hari 2 Malam',
      status: 'Aktif',
      rating: 4.8,
      reviewCount: 50,
      description: 'Nikmati wisata budaya dan sejarah di Rumah Ayu Ting-Ting.',
      images: [
        'https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=800',
      ],
      highlights: ['🎓 Tour Guide Sertifikasi', '📷 Dokumentasi Lengkap', '🚌 Armada Transport AC'],
      itinerary: [
        'Hari 1: Penjemputan - Tour Rumah Ayu Ting-Ting & Wisata Budaya',
        'Hari 2: Eksplorasi Kuliner & Oleh-oleh',
        'Hari 3: Pengantaran Kembali',
      ],
      facilities: ['Mobil Transport AC', 'Tour Guide', 'Makan Pagi'],
      includes: ['Tiket Masuk', 'Air Mineral'],
      excludes: ['Pengeluaran Pribadi'],
      meetingPoint: 'Titik Kumpul Jawa Barat',
    ),
    TripPackage(
      id: 2,
      providerId: 1,
      providerName: 'Wisata Nusantara',
      providerAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200',
      name: 'Wisata Margo City',
      category: 'City Tour',
      tripType: 'Open Trip',
      destination: 'Jawa Barat',
      price: 120000,
      quotaUsed: 2,
      quotaMax: 12,
      minParticipants: 4,
      availableSeats: 10,
      schedule: '16 September 2026 - 17 September 2026 (2 Hari)',
      duration: '2 Hari 1 Malam',
      status: 'Aktif',
      rating: 5.0,
      reviewCount: 50,
      description: 'Jelajahi keindahan dan pusat hiburan Margo City.',
      images: [
        'https://images.unsplash.com/photo-1506929562872-bb421503ef21?w=800',
      ],
      highlights: ['🎓 Tour Guide Sertifikasi', '📷 Dokumentasi Lengkap', '🚌 Armada Transport AC'],
      itinerary: [
        'Hari 1: Penjemputan - City Tour Margo City',
        'Hari 2: Shopping & Dropoff',
      ],
      facilities: ['Transport AC', 'Guide', 'Snack'],
      includes: ['Tiket Masuk'],
      excludes: ['Pengeluaran Pribadi'],
      meetingPoint: 'Titik Kumpul Jawa Barat',
    ),
    TripPackage(
      id: 3,
      providerId: 1,
      providerName: 'Wisata Nusantara',
      providerAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200',
      name: 'Bandung City Tour',
      category: 'City Tour',
      tripType: 'Open Trip',
      destination: 'Bandung, Jawa Barat',
      price: 420000,
      quotaUsed: 3,
      quotaMax: 15,
      minParticipants: 4,
      availableSeats: 12,
      schedule: '16 September 2026 - 17 September 2026 (2 Hari)',
      duration: '2 Hari 1 Malam',
      status: 'Aktif',
      rating: 4.0,
      reviewCount: 50,
      description: 'Kelilingi destinasi favorit di Kota Bandung.',
      images: [
        'https://images.unsplash.com/photo-1506929562872-bb421503ef21?w=800',
      ],
      highlights: ['🎓 Tour Guide Sertifikasi', '📷 Dokumentasi Lengkap', '🚌 Armada Transport AC'],
      itinerary: [
        'Hari 1: Gedung Sate - Braga - Farmhouse',
        'Hari 2: Oleh-oleh & Pengantaran Stasiun',
      ],
      facilities: ['Mobil HiAce AC', 'Hotel Bintang 3', 'Makan Pagi'],
      includes: ['Tiket Wisata', 'Air Mineral'],
      excludes: ['Pengeluaran Pribadi'],
      meetingPoint: 'Stasiun Bandung',
    ),
    TripPackage(
      id: 4,
      providerId: 1,
      providerName: 'Wisata Nusantara',
      providerAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200',
      name: 'Trip Curug Cilember',
      category: 'Curug',
      tripType: 'Open Trip',
      destination: 'Bogor, Jawa Barat',
      price: 275000,
      quotaUsed: 4,
      quotaMax: 10,
      minParticipants: 5,
      availableSeats: 6,
      schedule: '16 September 2026 - 17 September 2026 (2 Hari)',
      duration: '2 Hari 1 Malam',
      status: 'Aktif',
      rating: 4.0,
      reviewCount: 50,
      description: 'Wisata 7 air terjun Curug Cilember Bogor.',
      images: [
        'https://images.unsplash.com/photo-1516690561799-46d8f74f9abf?w=800',
      ],
      highlights: ['🌊 7 Tingkat Air Terjun', '🌲 Hutan Pinus Asri', '🔥 Api Unggun Malam'],
      itinerary: [
        'Hari 1: Trekking Curug 7 Cilember - Camping Ground',
        'Hari 2: Taman Kupu-Kupu - Transfer Stasiun',
      ],
      facilities: ['Tenda Camping', 'Makan 2x', 'Pemandu'],
      includes: ['Tiket Wisata'],
      excludes: ['Pengeluaran Pribadi'],
      meetingPoint: 'Stasiun Bogor',
    ),
    TripPackage(
      id: 5,
      providerId: 1,
      providerName: 'Wisata Nusantara',
      providerAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200',
      name: 'Baturaden 3D2N',
      category: 'Gunung',
      tripType: 'Private Trip',
      destination: 'Jawa Tengah',
      price: 500000,
      quotaUsed: 1,
      quotaMax: 10,
      minParticipants: 1,
      availableSeats: 9,
      schedule: 'Fleksibel (Pilihan Customer)',
      duration: '3 Hari 2 Malam',
      status: 'Aktif',
      rating: 5.0,
      reviewCount: 50,
      description: 'Wisata eksklusif Baturaden 3 hari 2 malam.',
      images: [
        'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800',
      ],
      highlights: ['🚗 Mobil Private & Driver', '👨‍💼 Pemandu & Dokumen Pro', '⏰ Jam Trip Fleksibel'],
      itinerary: [
        'Hari 1: Pickup - Check-in Resort Baturaden',
        'Hari 2: Pancuran Pitu - Lokawisata Baturaden',
        'Hari 3: Souvenir & Dropoff',
      ],
      facilities: ['Mobil Private', 'Driver', 'Resort AC'],
      includes: ['Tiket Wisata'],
      excludes: ['Pengeluaran Pribadi'],
      meetingPoint: 'Stasiun Purwokerto',
    ),
    TripPackage(
      id: 6,
      providerId: 1,
      providerName: 'Wisata Nusantara',
      providerAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200',
      name: 'Honeymoon Island Sunset Tidung 3D2N',
      category: 'Pantai',
      tripType: 'Honeymoon',
      destination: 'Kepulauan Seribu, Jakarta',
      price: 1650000,
      quotaUsed: 2,
      quotaMax: 2,
      minParticipants: 2,
      availableSeats: 2,
      schedule: 'Fleksibel (Pilihan Customer)',
      duration: '3 Hari 2 Malam',
      status: 'Aktif',
      rating: 5.0,
      reviewCount: 50,
      description: 'Honeymoon romantis di Pulau Tidung Kepulauan Seribu.',
      images: [
        'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800',
      ],
      highlights: ['🥞 Floating Breakfast', '🏡 Private Pool Villa', '🍷 Candlelight Dinner'],
      itinerary: [
        'Hari 1: Boat Ancol - Water Cottage Check-in',
        'Hari 2: Private Snorkeling & Sunset Dinner',
        'Hari 3: Kembali ke Jakarta',
      ],
      facilities: ['Cottage Over Sea', 'Private Boat', 'Makan 3x'],
      includes: ['Tiket Speedboat'],
      excludes: ['Pengeluaran Pribadi'],
      meetingPoint: 'Marina Ancol, Jakarta',
    ),
    TripPackage(
      id: 7,
      providerId: 1,
      providerName: 'Wisata Nusantara',
      providerAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200',
      name: 'Honeymoon Romantic Bali Villa 3D2N',
      category: 'Pantai',
      tripType: 'Honeymoon',
      destination: 'Bali',
      price: 2950000,
      quotaUsed: 2,
      quotaMax: 2,
      minParticipants: 2,
      availableSeats: 2,
      schedule: 'Fleksibel (Pilihan Customer)',
      duration: '3 Hari 2 Malam',
      status: 'Aktif',
      rating: 5.0,
      reviewCount: 50,
      description: 'Paket honeymoon romantis di villa private Bali.',
      images: [
        'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800',
      ],
      highlights: ['🥞 Floating Breakfast', '🏡 Private Pool Villa', '🍷 Candlelight Dinner'],
      itinerary: [
        'Hari 1: Airport Pickup - Check-in Private Villa',
        'Hari 2: Uluwatu Sunset & Candlelight Dinner',
        'Hari 3: Airport Drop',
      ],
      facilities: ['Private Villa Pool', 'Innova + Driver', 'Romantic Dinner'],
      includes: ['Flowers Setup'],
      excludes: ['Tiket Pesawat'],
      meetingPoint: 'Bandara Ngurah Rai Bali',
    ),
    TripPackage(
      id: 8,
      providerId: 1,
      providerName: 'Wisata Nusantara',
      providerAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200',
      name: 'Private Trip Wisata Raja Ampat 4D3N',
      category: 'Diving & Snorkeling',
      tripType: 'Private Trip',
      destination: 'Papua Barat',
      price: 3850000,
      quotaUsed: 1,
      quotaMax: 8,
      minParticipants: 1,
      availableSeats: 7,
      schedule: 'Fleksibel (Pilihan Customer)',
      duration: '4 Hari 3 Malam',
      status: 'Aktif',
      rating: 5.0,
      reviewCount: 50,
      description: 'Jelajahi surga bawah laut Raja Ampat Papua Barat.',
      images: [
        'https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=800',
      ],
      highlights: ['🚗 Mobil Private & Driver', '👨‍💼 Pemandu & Dokumen Pro', '⏰ Jam Trip Fleksibel'],
      itinerary: [
        'Hari 1: Sorong Pickup - Speedboat Waisai',
        'Hari 2: Wayag & Piaynemo Trekking',
        'Hari 3: Snorkeling Manta Point',
        'Hari 4: Sorong Dropoff',
      ],
      facilities: ['Private Speedboat', 'Resort AC', 'Alat Diving'],
      includes: ['Pin Raja Ampat'],
      excludes: ['Tiket Pesawat'],
      meetingPoint: 'Bandara Sorong',
    ),
    TripPackage(
      id: 9,
      providerId: 1,
      providerName: 'Wisata Nusantara',
      providerAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200',
      name: 'Pantai Muara Gembong',
      category: 'Pantai',
      tripType: 'Corporate',
      destination: 'Jawa Barat',
      price: 150000,
      quotaUsed: 10,
      quotaMax: 50,
      minParticipants: 10,
      availableSeats: 40,
      schedule: 'Fleksibel (Pilihan Group)',
      duration: '1 Hari',
      status: 'Aktif',
      rating: 5.0,
      reviewCount: 50,
      description: 'Wisata pantai dan ekosistem mangrove Pantai Muara Gembong.',
      images: [
        'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800',
      ],
      highlights: ['🪸 Snorkeling Terumbu Karang', '📷 Free Foto Underwater', '🚲 Sepeda Keliling Pulau'],
      itinerary: [
        'Hari 1: Mangrove Tour - Snorkeling - Sepeda Santai',
      ],
      facilities: ['Perahu Tour', 'Makan Siang', 'Alat Snorkeling'],
      includes: ['Dokumentasi Underwater'],
      excludes: ['Pengeluaran Pribadi'],
      meetingPoint: 'Muara Gembong Jawa Barat',
    ),
    TripPackage(
      id: 10,
      providerId: 1,
      providerName: 'Wisata Nusantara',
      providerAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200',
      name: 'Corporate Team Building Bogor 2D1N',
      category: 'Keluarga Santai',
      tripType: 'Corporate',
      destination: 'Bogor, Jawa Barat',
      price: 680000,
      quotaUsed: 10,
      quotaMax: 100,
      minParticipants: 10,
      availableSeats: 90,
      schedule: 'Fleksibel (Pilihan Group)',
      duration: '2 Hari 1 Malam',
      status: 'Aktif',
      rating: 4.9,
      reviewCount: 50,
      description: 'Kegiatan team building & gathering perusahaan di Bogor.',
      images: [
        'https://images.unsplash.com/photo-1506929562872-bb421503ef21?w=800',
      ],
      highlights: ['🎯 Outbound Team Building', '🚌 Bus Luxury VIP', '🍢 Gala Dinner & BBQ'],
      itinerary: [
        'Hari 1: Arrival Bogor - Outbound Games - Gala Night',
        'Hari 2: Closing & Return',
      ],
      facilities: ['Bus VIP', 'Hotel Bintang 4', 'Master Games'],
      includes: ['Banner Custom', 'Dokumentasi'],
      excludes: ['Pengeluaran Pribadi'],
      meetingPoint: 'Kantor Perusahaan',
    ),
    TripPackage(
      id: 11,
      providerId: 1,
      providerName: 'Wisata Nusantara',
      providerAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200',
      name: 'Corporate Gathering & Outbound Bandung',
      category: 'Keluarga Santai',
      tripType: 'Corporate',
      destination: 'Bandung, Jawa Barat',
      price: 750000,
      quotaUsed: 10,
      quotaMax: 100,
      minParticipants: 10,
      availableSeats: 90,
      schedule: 'Fleksibel (Pilihan Group)',
      duration: '2 Hari 1 Malam',
      status: 'Aktif',
      rating: 4.9,
      reviewCount: 50,
      description: 'Acara gathering outbound kantor seru di Bandung.',
      images: [
        'https://images.unsplash.com/photo-1506929562872-bb421503ef21?w=800',
      ],
      highlights: ['🎯 Outbound Team Building', '🚌 Bus Luxury VIP', '🍢 Gala Dinner & BBQ'],
      itinerary: [
        'Hari 1: Pickup - Outbound Lembang - Gala Dinner',
        'Hari 2: Shopping & Return',
      ],
      facilities: ['Bus VIP', 'Resort AC', 'Sound System'],
      includes: ['Banner Custom'],
      excludes: ['Pengeluaran Pribadi'],
      meetingPoint: 'Kantor Perusahaan',
    ),
    TripPackage(
      id: 12,
      providerId: 1,
      providerName: 'Wisata Nusantara',
      providerAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200',
      name: 'Family Nature Retreat Cilember 2D1N',
      category: 'Curug',
      tripType: 'Family',
      destination: 'Bogor, Jawa Barat',
      price: 650000,
      quotaUsed: 5,
      quotaMax: 20,
      minParticipants: 5,
      availableSeats: 15,
      schedule: 'Fleksibel (Pilihan Keluarga)',
      duration: '2 Hari 1 Malam',
      status: 'Aktif',
      rating: 4.9,
      reviewCount: 50,
      description: 'Liburan keluarga santai menikmati alam Cilember Bogor.',
      images: [
        'https://images.unsplash.com/photo-1516690561799-46d8f74f9abf?w=800',
      ],
      highlights: ['🌊 7 Tingkat Air Terjun', '🌲 Hutan Pinus Asri', '🔥 Api Unggun Malam'],
      itinerary: [
        'Hari 1: Pickup - Villa Cilember - BBQ Family',
        'Hari 2: Curug Tour - Return',
      ],
      facilities: ['Villa 3 Kamar', 'BBQ Set'],
      includes: ['Tiket Wisata'],
      excludes: ['Pengeluaran Pribadi'],
      meetingPoint: 'Stasiun Bogor',
    ),
  ];
}
